/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNutricionistaRouteRouteImport } from './routes/_authenticated/nutricionista/route'
import { Route as AuthenticatedPacienteRouteRouteImport } from './routes/_authenticated/paciente/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutricionistaRouteRoute =
  AuthenticatedNutricionistaRouteRouteImport.update({
    id: '/nutricionista',
    path: '/nutricionista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacienteRouteRoute =
  AuthenticatedPacienteRouteRouteImport.update({
    id: '/paciente',
    path: '/paciente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nutricionista': typeof AuthenticatedNutricionistaRouteRoute
  '/paciente': typeof AuthenticatedPacienteRouteRoute
  '/inicio': typeof AuthenticatedInicioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nutricionista': typeof AuthenticatedNutricionistaRouteRoute
  '/paciente': typeof AuthenticatedPacienteRouteRoute
  '/inicio': typeof AuthenticatedInicioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/nutricionista': typeof AuthenticatedNutricionistaRouteRoute
  '/_authenticated/paciente': typeof AuthenticatedPacienteRouteRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/nutricionista' | '/paciente' | '/inicio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/nutricionista' | '/paciente' | '/inicio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/nutricionista'
    | '/_authenticated/paciente'
    | '/_authenticated/inicio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutricionista': {
      id: '/_authenticated/nutricionista'
      path: '/nutricionista'
      fullPath: '/nutricionista'
      preLoaderRoute: typeof AuthenticatedNutricionistaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paciente': {
      id: '/_authenticated/paciente'
      path: '/paciente'
      fullPath: '/paciente'
      preLoaderRoute: typeof AuthenticatedPacienteRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNutricionistaRouteRoute: typeof AuthenticatedNutricionistaRouteRoute
  AuthenticatedPacienteRouteRoute: typeof AuthenticatedPacienteRouteRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNutricionistaRouteRoute: AuthenticatedNutricionistaRouteRoute,
  AuthenticatedPacienteRouteRoute: AuthenticatedPacienteRouteRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
